// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD6aO24JCtP4R1fIVwCC3YmsC70i4tUotE',
    appId: '1:1073921103543:web:e836c15f8f720428bd9f32',
    messagingSenderId: '1073921103543',
    projectId: 'mentorme-f5b0f',
    authDomain: 'mentorme-f5b0f.firebaseapp.com',
    storageBucket: 'mentorme-f5b0f.appspot.com',
    measurementId: 'G-44YYBPDBYP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8hctVHvdxary4IC7bZNs9kHuPiiB99UE',
    appId: '1:1073921103543:android:8d2fe48e8b0508b3bd9f32',
    messagingSenderId: '1073921103543',
    projectId: 'mentorme-f5b0f',
    storageBucket: 'mentorme-f5b0f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEXfRFeuCW5VL2-XtMlaHP-WToJk41Nr4',
    appId: '1:1073921103543:ios:45bb2564fd6cdfafbd9f32',
    messagingSenderId: '1073921103543',
    projectId: 'mentorme-f5b0f',
    storageBucket: 'mentorme-f5b0f.appspot.com',
    iosBundleId: 'com.example.mentorme',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEXfRFeuCW5VL2-XtMlaHP-WToJk41Nr4',
    appId: '1:1073921103543:ios:45bb2564fd6cdfafbd9f32',
    messagingSenderId: '1073921103543',
    projectId: 'mentorme-f5b0f',
    storageBucket: 'mentorme-f5b0f.appspot.com',
    iosBundleId: 'com.example.mentorme',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6aO24JCtP4R1fIVwCC3YmsC70i4tUotE',
    appId: '1:1073921103543:web:f9c745cc52d451ccbd9f32',
    messagingSenderId: '1073921103543',
    projectId: 'mentorme-f5b0f',
    authDomain: 'mentorme-f5b0f.firebaseapp.com',
    storageBucket: 'mentorme-f5b0f.appspot.com',
    measurementId: 'G-DN0W1VLK1P',
  );
}
